server:
  port: 10001
spring:
  profiles:
    active: dev
  application:
    name: order-api
management:
  server:
    port: 10002
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
debug: true #显示debug日志信息
##日志配置 默認
#logging:
#  config: classpath:logback.xml




